### ISSUE TITLE
PyTorch Transformer Encoder

### ISSUE THREAD

**Issue by thisisashukla** [thisisashukla/inclusive-ai#11]
**Sub-tasks**:

- [ ] Coding the feature extractor for video tensors - 4 h
- [ ] Video tensor padding + masking - 2 h
- [ ] Positional encoding - 1 h
- [ ] Transformer encoder - 2 h
- [ ] Update Ankita on the docker script - 1 h
- [ ] Update docker script for the changes in the code - 10 h

**Success Criteria**:

- [ ] We should get a encoded embedding matrix is we pass a set of image frames
